apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reearth-proto
  namespace: reearth
  description: Centralized Protocol Buffer definitions for Re:Earth internal APIs
  annotations:
    github.com/project-slug: reearth/reearth-proto
  links:
  - url: https://github.com/reearth/reearth-proto
    title: GitHub
    icon: github
  tags:
  - protobuf
  - schema
  - shared
spec:
  type: library
  lifecycle: production
  owner: reearth/cto-office
